// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8zQrPifcAgVM6u6BQ0VbOH-xxsdZe8Lk',
    appId: '1:1082557842003:web:0f6f0d200e93673512fca6',
    messagingSenderId: '1082557842003',
    projectId: 'sign-in-9b224',
    authDomain: 'sign-in-9b224.firebaseapp.com',
    storageBucket: 'sign-in-9b224.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQTA90bxxQTWjilh5a6hmSoLKuFat448M',
    appId: '1:1082557842003:android:daa89e79625cf23812fca6',
    messagingSenderId: '1082557842003',
    projectId: 'sign-in-9b224',
    storageBucket: 'sign-in-9b224.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0chUIGc2T11tkMOo-8HnSVQXbxmzlFqo',
    appId: '1:1082557842003:ios:705b33dfc66b517c12fca6',
    messagingSenderId: '1082557842003',
    projectId: 'sign-in-9b224',
    storageBucket: 'sign-in-9b224.appspot.com',
    androidClientId: '1082557842003-uqqb52c4cl6h0dm5vuk3uj9s520jf4ln.apps.googleusercontent.com',
    iosClientId: '1082557842003-4c69a1iuhnoo9cqehtqi6ma4lvdiidk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.agri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0chUIGc2T11tkMOo-8HnSVQXbxmzlFqo',
    appId: '1:1082557842003:ios:449ced876bbb439612fca6',
    messagingSenderId: '1082557842003',
    projectId: 'sign-in-9b224',
    storageBucket: 'sign-in-9b224.appspot.com',
    androidClientId: '1082557842003-uqqb52c4cl6h0dm5vuk3uj9s520jf4ln.apps.googleusercontent.com',
    iosClientId: '1082557842003-99ihevmrpk42om24euo24md3k75ne2lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.agri.RunnerTests',
  );
}
